test:
  adapter: postgresql
  database: mapaafrodescendente_test
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4

development:
  adapter: postgresql
  database: mapaafrodescendente_development
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4

production:
  adapter: postgresql
  database: mapaafrodescendente_production
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4
