test:
  adapter: postgresql
  database: mapaafrodescendente
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4

development:
  adapter: postgresql
  database: mapaafrodescendente
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4

production:
  adapter: postgresql
  database: mapaafrodescendente
  host: localhost
  username: mapaafrodescendente
  password: mapaafrodescendente
  encoding: utf8
  pool: 4
